#
# ---------------------------
#   ${artifactId} v${project.version}
# ---------------------------
#
backend:
  type: json

currency:
  name:
    singular: dollar
    plural: dollars
  balance-format: '{1} {2}'

  custom-format:
    enabled: false
    format: '0.00'
    grouping: 3
    decimal-separator: '.'
    grouping-separator: ','

chat:
  prefix: '&b[&9Economy&b]&r '

economy:
  start-balance: 0.0
  notify-start-balance: true
  server-account: '$SERVER$'

locale-override: false
debug: false
